//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OficinasService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="oficina", Namespace="http://schemas.datacontract.org/2004/07/ControlBoxWCF.Models.Entities")]
    public partial class oficina : object
    {
        
        private string _cor_nombreField;
        
        private int _gir_girosField;
        
        private int _ofi_corresponsal_idField;
        
        private string _ofi_nombreField;
        
        private int _ofi_oficina_idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _cor_nombre
        {
            get
            {
                return this._cor_nombreField;
            }
            set
            {
                this._cor_nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _gir_giros
        {
            get
            {
                return this._gir_girosField;
            }
            set
            {
                this._gir_girosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _ofi_corresponsal_id
        {
            get
            {
                return this._ofi_corresponsal_idField;
            }
            set
            {
                this._ofi_corresponsal_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _ofi_nombre
        {
            get
            {
                return this._ofi_nombreField;
            }
            set
            {
                this._ofi_nombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int _ofi_oficina_id
        {
            get
            {
                return this._ofi_oficina_idField;
            }
            set
            {
                this._ofi_oficina_idField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OficinasService.IOficinas")]
    public interface IOficinas
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOficinas/GetDataOficinas", ReplyAction="http://tempuri.org/IOficinas/GetDataOficinasResponse")]
        OficinasService.oficina[] GetDataOficinas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOficinas/GetDataOficinas", ReplyAction="http://tempuri.org/IOficinas/GetDataOficinasResponse")]
        System.Threading.Tasks.Task<OficinasService.oficina[]> GetDataOficinasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOficinas/GetAllOficinas", ReplyAction="http://tempuri.org/IOficinas/GetAllOficinasResponse")]
        OficinasService.oficina[] GetAllOficinas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOficinas/GetAllOficinas", ReplyAction="http://tempuri.org/IOficinas/GetAllOficinasResponse")]
        System.Threading.Tasks.Task<OficinasService.oficina[]> GetAllOficinasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOficinas/AddDataOficinas", ReplyAction="http://tempuri.org/IOficinas/AddDataOficinasResponse")]
        string AddDataOficinas(OficinasService.oficina ofi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOficinas/AddDataOficinas", ReplyAction="http://tempuri.org/IOficinas/AddDataOficinasResponse")]
        System.Threading.Tasks.Task<string> AddDataOficinasAsync(OficinasService.oficina ofi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOficinas/UpdateDataOficinas", ReplyAction="http://tempuri.org/IOficinas/UpdateDataOficinasResponse")]
        string UpdateDataOficinas(OficinasService.oficina ofi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOficinas/UpdateDataOficinas", ReplyAction="http://tempuri.org/IOficinas/UpdateDataOficinasResponse")]
        System.Threading.Tasks.Task<string> UpdateDataOficinasAsync(OficinasService.oficina ofi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOficinas/DeleteOficinas", ReplyAction="http://tempuri.org/IOficinas/DeleteOficinasResponse")]
        string DeleteOficinas(OficinasService.oficina ofi);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOficinas/DeleteOficinas", ReplyAction="http://tempuri.org/IOficinas/DeleteOficinasResponse")]
        System.Threading.Tasks.Task<string> DeleteOficinasAsync(OficinasService.oficina ofi);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IOficinasChannel : OficinasService.IOficinas, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class OficinasClient : System.ServiceModel.ClientBase<OficinasService.IOficinas>, OficinasService.IOficinas
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OficinasClient() : 
                base(OficinasClient.GetDefaultBinding(), OficinasClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IOficinas.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OficinasClient(EndpointConfiguration endpointConfiguration) : 
                base(OficinasClient.GetBindingForEndpoint(endpointConfiguration), OficinasClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OficinasClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OficinasClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OficinasClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OficinasClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OficinasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public OficinasService.oficina[] GetDataOficinas()
        {
            return base.Channel.GetDataOficinas();
        }
        
        public System.Threading.Tasks.Task<OficinasService.oficina[]> GetDataOficinasAsync()
        {
            return base.Channel.GetDataOficinasAsync();
        }
        
        public OficinasService.oficina[] GetAllOficinas()
        {
            return base.Channel.GetAllOficinas();
        }
        
        public System.Threading.Tasks.Task<OficinasService.oficina[]> GetAllOficinasAsync()
        {
            return base.Channel.GetAllOficinasAsync();
        }
        
        public string AddDataOficinas(OficinasService.oficina ofi)
        {
            return base.Channel.AddDataOficinas(ofi);
        }
        
        public System.Threading.Tasks.Task<string> AddDataOficinasAsync(OficinasService.oficina ofi)
        {
            return base.Channel.AddDataOficinasAsync(ofi);
        }
        
        public string UpdateDataOficinas(OficinasService.oficina ofi)
        {
            return base.Channel.UpdateDataOficinas(ofi);
        }
        
        public System.Threading.Tasks.Task<string> UpdateDataOficinasAsync(OficinasService.oficina ofi)
        {
            return base.Channel.UpdateDataOficinasAsync(ofi);
        }
        
        public string DeleteOficinas(OficinasService.oficina ofi)
        {
            return base.Channel.DeleteOficinas(ofi);
        }
        
        public System.Threading.Tasks.Task<string> DeleteOficinasAsync(OficinasService.oficina ofi)
        {
            return base.Channel.DeleteOficinasAsync(ofi);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOficinas))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IOficinas))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:58418/Oficinas.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return OficinasClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IOficinas);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return OficinasClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IOficinas);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IOficinas,
        }
    }
}
